### ISSUE TITLE
when 'Back' button is pressed it creates another more cards

### ISSUE THREAD

**Issue by AsimNet** [alchimya/iOS-Google-Now-Cards-Interface-#1]
Hi 
http://quick.as/g9XJu94Z5
please watch the video

**Comment by alchimya** [comment]
Hi,
if you are loading the cards into the viewDidAppear, you have to test if the cards into your L3SDKCardsView instance have already been loaded.

Example:

-(void)viewDidAppear:(BOOL)animated{
    [super viewDidAppear:animated];

```
if (self.containerView.cards.count!=0) {
    [self.containerView drawView];
    return;
}
[self addCards];
```

}

I uploaded example project on the repository (see viewDidAppear into the ViewController.m file).
Anyway, if my answer does not solve your problem, send me a project with your test case.
Regards,
Domenico
